---
# ========================================
# cPanel Git Deployment Configuration (SUBFOLDER TEST)
# ========================================
# Deploy automat din: app/public/wp-content/
# Către destinație: public_html/test/wp-content/
# ========================================

deployment:
  tasks:
    # ========================================
    # TASK 1: Backup înainte de deploy (SAFETY - folderul test)
    # ========================================
    - export TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    - export BACKUP_DIR=$HOME/backups/test_site
    - mkdir -p $BACKUP_DIR
    - echo "💾 Creating backup for /public_html/test/..."
    - tar -czf $BACKUP_DIR/wp-content-test-backup-$TIMESTAMP.tar.gz $HOME/public_html/test/wp-content 2>/dev/null || true
    - echo "✅ Backup saved: wp-content-test-backup-$TIMESTAMP.tar.gz"
    
    # ========================================
    # TASK 2: Deploy PLUGINS (Sursă: app/public/wp-content/)
    # ========================================
    - echo "🔄 Deploying plugins from app/public/ path to /test/..."
    
    # Plugin 1: webgsm-b2b-pricing
    - /bin/cp -rf $HOME/repositories/webgsm/app/public/wp-content/plugins/webgsm-b2b-pricing $HOME/public_html/test/wp-content/plugins/
    
    # Plugin 2: webgsm-checkout-pro
    - /bin/cp -rf $HOME/repositories/webgsm/app/public/wp-content/plugins/webgsm-checkout-pro $HOME/public_html/test/wp-content/plugins/
    
    # Plugin 3: webgsm-customer-tiers
    - /bin/cp -rf $HOME/repositories/webgsm/app/public/wp-content/plugins/webgsm-customer-tiers $HOME/public_html/test/wp-content/plugins/ 2>/dev/null || true
    
    - echo "✅ Plugins deployed to /test/!"
    
    # ========================================
    # TASK 3: Deploy THEME (Sursă: app/public/wp-content/)
    # ========================================
    - echo "🔄 Deploying theme to /test/..."
    - /bin/cp -rf $HOME/repositories/webgsm/app/public/wp-content/themes/martfury-child $HOME/public_html/test/wp-content/themes/
    - echo "✅ Theme deployed to /test/!"
    
    # ========================================
    # TASK 4: Cleanup & Permissions (In /test/)
    # ========================================
    - echo "🧹 Cleaning up /test/ files..."
    - find $HOME/public_html/test/wp-content/plugins/ -name "*.md" -type f -delete 2>/dev/null || true
    - find $HOME/public_html/test/wp-content/themes/martfury-child/ -name "*.md" -type f -delete 2>/dev/null || true
    
    # Set permissions
    - find $HOME/public_html/test/wp-content/plugins/ -type d -exec chmod 755 {} \;
    - find $HOME/public_html/test/wp-content/plugins/ -type f -exec chmod 644 {} \;
    - find $HOME/public_html/test/wp-content/themes/martfury-child/ -type d -exec chmod 755 {} \;
    - find $HOME/public_html/test/wp-content/themes/martfury-child/ -type f -exec chmod 644 {} \;
    
    # ========================================
    # TASK 5: Clear Cache & Force Reload (In /test/)
    # ========================================
    - echo "🗑️ Clearing cache for /test/..."
    - rm -rf $HOME/public_html/test/wp-content/cache/* 2>/dev/null || true
    - touch $HOME/public_html/test/wp-content/plugins/webgsm-b2b-pricing/webgsm-b2b-pricing.php
    
    # WP-CLI pentru subfolderul /test/
    - cd $HOME/public_html/test && wp cache flush 2>/dev/null || echo "⚠️ WP-CLI not available in /test/"
    
    - echo "========================================="
    - echo "✅ DEPLOYMENT TO /TEST/ COMPLETE!"
    - echo "========================================="
